//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cart_ArathyPillai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cart
    {
        public int cartid { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> FKproductid { get; set; }
        public Nullable<int> FKuserid { get; set; }
        public Nullable<bool> orderplaces { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
