//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cart_ArathyPillai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_Cart = new HashSet<tbl_Cart>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public Nullable<int> productquantity { get; set; }
        public Nullable<decimal> productprice { get; set; }
        public string productdescription { get; set; }
        public string productimg { get; set; }
        public Nullable<int> FKsubcatid { get; set; }
    
        public virtual tbl_SubCategory tbl_SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cart> tbl_Cart { get; set; }
    }
}
